### ISSUE TITLE
[schedy-feature] delay for window detection

### ISSUE THREAD

**Issue by hackex** [efficiosoft/hass-apps#80] opened 2023-01-15 21:16 UTC
I would like to integrate some delay between the time of closing a window and switching the heating thermostat on again. Both entities are connected in schedy.

I would like to do this because I think the heating may turn on too open as the thermostat head just got cold from venting the room... but giving some time to adjusting to the actual room temperature could solve it.

Is there a way to achieve that already?

**Comment by bob1de** [comment] 2023-01-15 21:25
Duplicate of #44

**Closed as completed by bob1de** 2023-01-15 21:25 UTC
