### ISSUE TITLE
Can't get install to work

### ISSUE THREAD

**Issue by whasf** [efficiosoft/hass-apps#52] opened 2020-08-14 20:25 UTC
Hello --

This seems really simple but I can't get the app to load in AppDaemon. I created the .py file and restart AppDaemon but it says it is ignoring it, and the only app I see is the "HelloWorld":

[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.6
 You are running the latest version of this add-on.
 System: HassOS 4.12  (amd64 / qemux86-64)
 Home Assistant Core: 0.114.0
 Home Assistant Supervisor: 232
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
Looking in links: https://wheels.hass.io/alpine-3.11/amd64/
Collecting hass-apps
  Downloading https://files.pythonhosted.org/packages/96/14/8e769a821c330e5ef698f813c11a19db69fde68ca4b7bea138248df1b0c3/hass_apps-0.20200319.0-py3-none-any.whl (54kB)
Requirement already satisfied: appdaemon<5,>=3.0 in /usr/lib/python3.8/site-packages (from hass-apps) (4.0.3)
Collecting observable~=1.0 (from hass-apps)
  Downloading https://files.pythonhosted.org/packages/45/7c/b4b63f447378e8a0ebcd338d90f9389f57fb23253127425beacf0129edcb/observable-1.0.3-py2.py3-none-any.whl
Collecting cached-property~=1.5 (from hass-apps)
  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Requirement already satisfied: voluptuous~=0.11 in /usr/lib/python3.8/site-packages (from hass-apps) (0.11.5)
Requirement already satisfied: aiohttp==3.6.2 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (3.6.2)
Requirement already satisfied: bcrypt==3.1.4 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (3.1.4)
Requirement already satisfied: astral==1.10.1 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (1.10.1)
Requirement already satisfied: feedparser in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (5.2.1)
Requirement already satisfied: pyyaml==5.1 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (5.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (2.8.1)
Requirement already satisfied: daemonize in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (2.5.0)
Requirement already satisfied: deepdiff in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (4.3.2)
Requirement already satisfied: pytz in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (2020.1)
Requirement already satisfied: python-socketio in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (4.5.1)
Requirement already satisfied: Jinja2==2.10.1 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (2.10.1)
Requirement already satisfied: yarl==1.1.0 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (1.1.0)
Requirement already satisfied: aiohttp-jinja2==0.15.0 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (0.15.0)
Requirement already satisfied: iso8601 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (0.1.12)
Requirement already satisfied: requests>=2.6.0 in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (2.23.0)
Requirement already satisfied: websocket-client in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (0.57.0)
Requirement already satisfied: pid in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (3.0.3)
Requirement already satisfied: paho-mqtt in /usr/lib/python3.8/site-packages (from appdaemon<5,>=3.0->hass-apps) (1.5.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/lib/python3.8/site-packages (from aiohttp==3.6.2->appdaemon<5,>=3.0->hass-apps) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3.8/site-packages (from aiohttp==3.6.2->appdaemon<5,>=3.0->hass-apps) (19.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/lib/python3.8/site-packages (from aiohttp==3.6.2->appdaemon<5,>=3.0->hass-apps) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.5 in /usr/lib/python3.8/site-packages (from aiohttp==3.6.2->appdaemon<5,>=3.0->hass-apps) (4.7.6)
Requirement already satisfied: cffi>=1.1 in /usr/lib/python3.8/site-packages (from bcrypt==3.1.4->appdaemon<5,>=3.0->hass-apps) (1.14.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.8/site-packages (from bcrypt==3.1.4->appdaemon<5,>=3.0->hass-apps) (1.14.0)
Requirement already satisfied: ordered-set>=3.1.1 in /usr/lib/python3.8/site-packages (from deepdiff->appdaemon<5,>=3.0->hass-apps) (4.0.1)
Requirement already satisfied: python-engineio>=3.9.0 in /usr/lib/python3.8/site-packages (from python-socketio->appdaemon<5,>=3.0->hass-apps) (3.12.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.8/site-packages (from Jinja2==2.10.1->appdaemon<5,>=3.0->hass-apps) (1.1.1)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3.8/site-packages (from yarl==1.1.0->appdaemon<5,>=3.0->hass-apps) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests>=2.6.0->appdaemon<5,>=3.0->hass-apps) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.6.0->appdaemon<5,>=3.0->hass-apps) (1.25.9)
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.1->bcrypt==3.1.4->appdaemon<5,>=3.0->hass-apps) (2.20)
Installing collected packages: observable, cached-property, hass-apps
Successfully installed cached-property-1.5.1 hass-apps-0.20200319.0 observable-1.0.3
WARNING: You are using pip version 19.2.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:19:39] INFO: Starting AppDaemon...
2020-08-14 22:19:40.598258 INFO AppDaemon: AppDaemon Version 4.0.3 starting
2020-08-14 22:19:40.598615 INFO AppDaemon: Python version is 3.8.2
2020-08-14 22:19:40.598941 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-08-14 22:19:40.599243 INFO AppDaemon: Added log: AppDaemon
2020-08-14 22:19:40.599523 INFO AppDaemon: Added log: Error
2020-08-14 22:19:40.599807 INFO AppDaemon: Added log: Access
2020-08-14 22:19:40.600071 INFO AppDaemon: Added log: Diag
2020-08-14 22:19:40.633513 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-08-14 22:19:40.671251 INFO HASS: HASS Plugin Initializing
2020-08-14 22:19:40.671786 INFO HASS: HASS Plugin initialization complete
2020-08-14 22:19:40.672931 INFO AppDaemon: Initializing HTTP
2020-08-14 22:19:40.673697 INFO AppDaemon: Using 'ws' for event stream
2020-08-14 22:19:40.698950 INFO AppDaemon: Starting API
2020-08-14 22:19:40.708513 INFO AppDaemon: Starting Admin Interface
2020-08-14 22:19:40.709227 INFO AppDaemon: Starting Dashboards
2020-08-14 22:19:40.743560 INFO HASS: Connected to Home Assistant 0.114.0
2020-08-14 22:19:40.762026 INFO AppDaemon: App 'hello_world' added
2020-08-14 22:19:40.764083 INFO AppDaemon: Found 1 total apps
2020-08-14 22:19:40.765091 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2020-08-14 22:19:40.766965 INFO AppDaemon: Running on port 5050
2020-08-14 22:19:40.820007 INFO HASS: Evaluating startup conditions
2020-08-14 22:19:40.863286 INFO AppDaemon: Got initial state from namespace default
2020-08-14 22:19:42.774166 INFO AppDaemon: Scheduler running in realtime
2020-08-14 22:19:42.778695 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
**2020-08-14 22:19:42.784570 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hass_apps_loader.py - ignoring**
2020-08-14 22:19:42.786573 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2020-08-14 22:19:42.796302 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-08-14 22:19:42.964309 INFO hello_world: Hello from AppDaemon
2020-08-14 22:19:42.966552 INFO hello_world: You are now ready to run Apps!
2020-08-14 22:19:42.971396 INFO AppDaemon: App initialization complete
2020-08-14 22:22:33.219501 INFO AppDaemon: New client Admin Browser connected
2020-08-14 22:22:38.834289 INFO AppDaemon: Unexpected client disconnection from Admin Browser

**Comment by efficiosoft** [comment] 2020-08-14 21:00
Hi,

You seem to haven't created a yaml config file for some app... please revisit the Configuration section in the Getting Started guide.

Closing this as it's not a bug.

Best regards
Robert

**Closed by efficiosoft** 2020-08-14 21:00 UTC
